### ISSUE TITLE
please check

### ISSUE THREAD

**Issue by RedZONERROR** [OmegaLolBro/HTMLSourceProtector#1]
Fatal error: Uncaught Error: Class "Html\Protector" not found in C:\xampp\htdocs\Admin\include\header.php:8 Stack trace: #0 C:\xampp\htdocs\Admin\index.php(2): include() #1 {main} thrown in C:\xampp\htdocs\Admin\include\header.php on line 8

**Comment by Arnvvch** [comment]
Hello,
Please enter the code so i can diagnose the error.

Have a nice day!

**Comment by Arnvvch** [comment]
Please try using require() instead of include()
